# simple GH actions workflow for testing with several Python versions
name: CI testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  pytester:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      #- name: Install package & dependencies
      #  run: |
      #    pip --version
      #    pip install -e . -U -q
      #    pip list

      - name: Run examples
        run: |
          python sample.py
          python multiexcept.py

  #tests-guardian:
  #  runs-on: ubuntu-latest
  #  needs: pytester
  #  if: always()
  #  steps:
  #    - run: echo "${{ needs.pytester.result }}"
  #    - name: failing...
  #      if: needs.pytester.result == 'failure'
  #      run: exit 1
  #    - name: cancelled or skipped...
  #      if: contains(fromJSON('["cancelled", "skipped"]'), needs.pytester.result)
  #      timeout-minutes: 1
  #      run: sleep 90
